// Titrate Alpha 0.2 – bytecode virtual machine: native function lookup
// Precision in every step – richie-rich90454, 2026

use super::super::super::value::NativeFn;
use super::{builtins, file, path, directory, system, net, time, regex, math,
            random, json, string, hash, encoding, subprocess, tempfile,
            thread, mutex, condvar, semaphore, atomic, socket, ssl, sqlite, mmap, zlib};

pub fn lookup_builtin_native(name: &str) -> Option<NativeFn> {
    match name {
        "println" => Some(builtins::native_println),
        "toString" => Some(builtins::native_to_string),
        "parseInt" => Some(builtins::native_parse_int),
        "Ok" => Some(builtins::native_ok),
        "Err" => Some(builtins::native_err),
        "File_readFile" => Some(file::native_file_read),
        "File_writeFile" => Some(file::native_file_write),
        "File_readLines" => Some(file::native_file_read_lines),
        "File_open" => Some(file::native_file_open),
        "File_readLine" => Some(file::native_file_read_line),
        "File_write" => Some(file::native_file_write_content),
        "File_close" => Some(file::native_file_close),
        "File_seek" => Some(file::native_file_seek),
        "File_tell" => Some(file::native_file_tell),
        "File_readBytes" => Some(file::native_file_read_bytes),
        "File_writeBytes" => Some(file::native_file_write_bytes),
        "File_lastModified" => Some(file::native_file_last_modified),
        "String_split" => Some(builtins::native_string_split),
        "Integer_parseOr" => Some(builtins::native_integer_parse_or),
        "String_trim" => Some(builtins::native_string_trim),
        "String_length" => Some(builtins::native_string_length),
        "Path_join" => Some(path::native_path_join),
        "Path_exists" => Some(path::native_path_exists),
        "Path_isFile" => Some(path::native_path_is_file),
        "Path_isDir" => Some(path::native_path_is_dir),
        "Path_basename" => Some(path::native_path_basename),
        "Path_dirname" => Some(path::native_path_dirname),
        "Path_extension" => Some(path::native_path_extension),
        "Dir_list" => Some(directory::native_dir_list),
        "Dir_create" => Some(directory::native_dir_create),
        "Dir_remove" => Some(directory::native_dir_remove),
        "Sys_args" => Some(system::native_sys_args),
        "Sys_env" => Some(system::native_sys_env),
        "Sys_setEnv" => Some(system::native_sys_set_env),
        "Sys_exit" => Some(system::native_sys_exit),
        "Sys_workingDir" => Some(system::native_sys_working_dir),
        "Sys_sleep" => Some(system::native_sys_sleep),
        "Net_connect" => Some(net::native_net_connect),
        "Net_send" => Some(net::native_net_send),
        "Net_receive" => Some(net::native_net_receive),
        "Net_bind" => Some(net::native_net_bind),
        "Net_accept" => Some(net::native_net_accept),
        "Net_close" => Some(net::native_net_close),
        "Http_get" => Some(net::native_http_get),
        "Http_post" => Some(net::native_http_post),
        "Http_put" => Some(net::native_http_put),
        "Http_delete" => Some(net::native_http_delete),
        "Http_patch" => Some(net::native_http_patch),
        "Http_head" => Some(net::native_http_head),
        "Time_now" => Some(time::native_time_now),
        "Time_sleep" => Some(time::native_time_sleep),
        "Time_format" => Some(time::native_time_format),
        "Time_getYear" => Some(time::native_time_get_year),
        "Time_getMonth" => Some(time::native_time_get_month),
        "Time_getDay" => Some(time::native_time_get_day),
        "Time_getHour" => Some(time::native_time_get_hour),
        "Time_getMinute" => Some(time::native_time_get_minute),
        "Time_getSecond" => Some(time::native_time_get_second),
        "Regex_match" => Some(regex::native_regex_match),
        "Regex_find" => Some(regex::native_regex_find),
        "Regex_replace" => Some(regex::native_regex_replace),
        "Math_sin" => Some(math::native_math_sin),
        "Math_cos" => Some(math::native_math_cos),
        "Math_tan" => Some(math::native_math_tan),
        "Math_asin" => Some(math::native_math_asin),
        "Math_acos" => Some(math::native_math_acos),
        "Math_atan" => Some(math::native_math_atan),
        "Math_atan2" => Some(math::native_math_atan2),
        "Math_ln" => Some(math::native_math_ln),
        "Math_log10" => Some(math::native_math_log10),
        "Math_log2" => Some(math::native_math_log2),
        "Math_exp" => Some(math::native_math_exp),
        "Math_pow" => Some(math::native_math_pow),
        "Math_sqrt" => Some(math::native_math_sqrt),
        "Math_cbrt" => Some(math::native_math_cbrt),
        "Math_abs" => Some(math::native_math_abs),
        "Math_absInt" => Some(math::native_math_abs_int),
        "Math_floor" => Some(math::native_math_floor),
        "Math_ceil" => Some(math::native_math_ceil),
        "Math_round" => Some(math::native_math_round),
        "Math_inf" => Some(math::native_math_inf),
        "Math_nan" => Some(math::native_math_nan),
        "Math_maxDouble" => Some(math::native_math_max_double),
        "Math_minDouble" => Some(math::native_math_min_double),
        "Math_maxInt" => Some(math::native_math_max_int),
        "Math_minInt" => Some(math::native_math_min_int),
        "Random_seed" => Some(random::native_random_seed),
        "Random_nextLong" => Some(random::native_random_next_long),
        "Json_parse" => Some(json::native_json_parse),
        "Json_stringify" => Some(json::native_json_stringify),
        "Env_get" => Some(system::native_env_get),
        "Env_set" => Some(system::native_env_set),
        "Env_vars" => Some(system::native_env_vars),
        "Fs_exists" => Some(system::native_fs_exists),
        "Fs_isFile" => Some(system::native_fs_is_file),
        "Fs_isDir" => Some(system::native_fs_is_dir),
        "Fs_size" => Some(system::native_fs_size),
        "Process_id" => Some(system::native_process_id),
        "Process_args" => Some(system::native_process_args),
        "Os_name" => Some(system::native_os_name),
        "Os_arch" => Some(system::native_os_arch),
        "Os_family" => Some(system::native_os_family),
        "String_trimStart" => Some(string::native_string_trim_start),
        "String_trimEnd" => Some(string::native_string_trim_end),
        "String_startsWith" => Some(string::native_string_starts_with),
        "String_endsWith" => Some(string::native_string_ends_with),
        "String_padLeft" => Some(string::native_string_pad_left),
        "String_padRight" => Some(string::native_string_pad_right),
        "String_toUpperCase" => Some(string::native_string_to_uppercase),
        "String_toLowerCase" => Some(string::native_string_to_lower_case),
        "String_replace" => Some(string::native_string_replace),
        "Hash_md5" => Some(hash::native_hash_md5),
        "Hash_sha1" => Some(hash::native_hash_sha1),
        "Hash_sha256" => Some(hash::native_hash_sha256),
        "Hash_sha384" => Some(hash::native_hash_sha384),
        "Hash_sha512" => Some(hash::native_hash_sha512),
        "Hash_sha3_256" => Some(hash::native_hash_sha3_256),
        "Hash_sha3_384" => Some(hash::native_hash_sha3_384),
        "Hash_sha3_512" => Some(hash::native_hash_sha3_512),
        "Hash_blake2b" => Some(hash::native_hash_blake2b),
        "Hash_blake2s" => Some(hash::native_hash_blake2s),
        "Hash_crc32" => Some(hash::native_hash_crc32),
        "Base64_encode" => Some(encoding::native_base64_encode),
        "Base64_decode" => Some(encoding::native_base64_decode),
        "Hex_encode" => Some(encoding::native_hex_encode),
        "Hex_decode" => Some(encoding::native_hex_decode),
        "Url_encode" => Some(encoding::native_url_encode),
        "Url_decode" => Some(encoding::native_url_decode),
        "Math_nextUp" => Some(math::native_math_next_up),
        "Math_nextDown" => Some(math::native_math_next_down),
        "Math_ulp" => Some(math::native_math_ulp),
        "Math_getExponent" => Some(math::native_math_get_exponent),
        "Math_scalb" => Some(math::native_math_scalb),
        "Math_random" => Some(math::native_math_random),
        "Math_negInf" => Some(math::native_math_neg_inf),
        "Regex_groupCount" => Some(regex::native_regex_group_count),
        "Regex_findGroups" => Some(regex::native_regex_find_groups),
        "Dir_walk" => Some(directory::native_dir_walk),
        "Dir_copy" => Some(directory::native_dir_copy),
        "Dir_move" => Some(directory::native_dir_move),
        "Time_dayOfWeek" => Some(time::native_time_day_of_week),
        "Time_dayOfYear" => Some(time::native_time_day_of_year),
        "Time_monotonic" => Some(time::native_time_monotonic),
        "Time_perfCounter" => Some(time::native_time_perf_counter),
        "Time_epochSeconds" => Some(time::native_time_epoch_seconds),
        "Double_parseDouble" => Some(builtins::native_double_parse_double),
        "Long_parseLong" => Some(builtins::native_long_parse_long),
        "Subprocess_run" => Some(subprocess::native_subprocess_run),
        "Subprocess_exec" => Some(subprocess::native_subprocess_exec),
        "Tempfile_create" => Some(tempfile::native_tempfile_create),

        // Thread natives
        "Thread_spawn" => Some(thread::native_thread_spawn),
        "Thread_join" => Some(thread::native_thread_join),
        "Thread_sleep" => Some(thread::native_thread_sleep),
        "Thread_yield" => Some(thread::native_thread_yield),
        "Thread_getId" => Some(thread::native_thread_get_id),
        "Thread_currentId" => Some(thread::native_thread_current_id),
        "Thread_detach" => Some(thread::native_thread_detach),

        // Mutex natives
        "Mutex_new" => Some(mutex::native_mutex_new),
        "Mutex_lock" => Some(mutex::native_mutex_lock),
        "Mutex_unlock" => Some(mutex::native_mutex_unlock),
        "Mutex_tryLock" => Some(mutex::native_mutex_try_lock),
        "RecursiveMutex_new" => Some(mutex::native_recursive_mutex_new),
        "RecursiveMutex_lock" => Some(mutex::native_recursive_mutex_lock),
        "RecursiveMutex_unlock" => Some(mutex::native_recursive_mutex_unlock),
        "RecursiveMutex_tryLock" => Some(mutex::native_recursive_mutex_try_lock),

        // Condvar natives
        "CondVar_new" => Some(condvar::native_cv_new),
        "CondVar_wait" => Some(condvar::native_cv_wait),
        "CondVar_waitFor" => Some(condvar::native_cv_wait_for),
        "CondVar_notifyOne" => Some(condvar::native_cv_notify_one),
        "CondVar_notifyAll" => Some(condvar::native_cv_notify_all),

        // Semaphore natives
        "Semaphore_new" => Some(semaphore::native_sem_new),
        "Semaphore_acquire" => Some(semaphore::native_sem_acquire),
        "Semaphore_release" => Some(semaphore::native_sem_release),
        "Semaphore_tryAcquire" => Some(semaphore::native_sem_try_acquire),
        "Semaphore_availablePermits" => Some(semaphore::native_sem_available_permits),

        // AtomicInt natives
        "AtomicInt_new" => Some(atomic::native_atomic_int_new),
        "AtomicInt_get" => Some(atomic::native_atomic_int_get),
        "AtomicInt_set" => Some(atomic::native_atomic_int_set),
        "AtomicInt_fetchAdd" => Some(atomic::native_atomic_int_fetch_add),
        "AtomicInt_fetchSub" => Some(atomic::native_atomic_int_fetch_sub),
        "AtomicInt_compareAndSwap" => Some(atomic::native_atomic_int_compare_and_swap),

        // AtomicBool natives
        "AtomicBool_new" => Some(atomic::native_atomic_bool_new),
        "AtomicBool_get" => Some(atomic::native_atomic_bool_get),
        "AtomicBool_set" => Some(atomic::native_atomic_bool_set),
        "AtomicBool_compareAndSwap" => Some(atomic::native_atomic_bool_compare_and_swap),

        // TCP Socket natives
        "Socket_new" => Some(socket::native_socket_new),
        "Socket_connect" => Some(socket::native_socket_connect),
        "Socket_bind" => Some(socket::native_socket_bind),
        "Socket_listen" => Some(socket::native_socket_listen),
        "Socket_accept" => Some(socket::native_socket_accept),
        "Socket_send" => Some(socket::native_socket_send),
        "Socket_recv" => Some(socket::native_socket_recv),
        "Socket_close" => Some(socket::native_socket_close),
        "Socket_setTimeout" => Some(socket::native_socket_set_timeout),
        "Socket_setNoDelay" => Some(socket::native_socket_set_no_delay),

        // UDP Socket natives
        "UdpSocket_new" => Some(socket::native_udp_socket_new),
        "UdpSocket_bind" => Some(socket::native_udp_socket_bind),
        "UdpSocket_sendTo" => Some(socket::native_udp_socket_send_to),
        "UdpSocket_recvFrom" => Some(socket::native_udp_socket_recv_from),
        "UdpSocket_close" => Some(socket::native_udp_socket_close),
        "UdpSocket_setTimeout" => Some(socket::native_udp_socket_set_timeout),
        "UdpSocket_lastSenderHost" => Some(socket::native_udp_socket_last_sender_host),
        "UdpSocket_lastSenderPort" => Some(socket::native_udp_socket_last_sender_port),
        "Socket_getAddrInfo" => Some(socket::native_socket_get_addr_info),

        // SSL natives (stubs)
        "Ssl_contextNew" => Some(ssl::native_ssl_context_new),
        "Ssl_connect" => Some(ssl::native_ssl_connect),
        "Ssl_send" => Some(ssl::native_ssl_send),
        "Ssl_recv" => Some(ssl::native_ssl_recv),
        "Ssl_close" => Some(ssl::native_ssl_close),
        "Ssl_peerCertificate" => Some(ssl::native_ssl_peer_certificate),
        "Ssl_contextClose" => Some(ssl::native_ssl_context_close),

        // SQLite natives (stubs)
        "Sqlite_open" => Some(sqlite::native_sqlite_open),
        "Sqlite_execute" => Some(sqlite::native_sqlite_execute),
        "Sqlite_query" => Some(sqlite::native_sqlite_query),
        "Sqlite_close" => Some(sqlite::native_sqlite_close),
        "Sqlite_lastInsertId" => Some(sqlite::native_sqlite_last_insert_id),
        "Sqlite_nextRow" => Some(sqlite::native_sqlite_next_row),
        "Sqlite_getInt" => Some(sqlite::native_sqlite_get_int),
        "Sqlite_getString" => Some(sqlite::native_sqlite_get_string),
        "Sqlite_getDouble" => Some(sqlite::native_sqlite_get_double),
        "Sqlite_columnCount" => Some(sqlite::native_sqlite_column_count),
        "Sqlite_columnName" => Some(sqlite::native_sqlite_column_name),
        "Sqlite_closeResult" => Some(sqlite::native_sqlite_close_result),

        // Mmap natives (stubs)
        "Mmap_open" => Some(mmap::native_mmap_open),
        "Mmap_close" => Some(mmap::native_mmap_close),
        "Mmap_get" => Some(mmap::native_mmap_get),
        "Mmap_set" => Some(mmap::native_mmap_set),
        "Mmap_size" => Some(mmap::native_mmap_size),
        "Mmap_flush" => Some(mmap::native_mmap_flush),

        // Signal natives (stubs)
        "Signal_register" => Some(system::native_signal_register),
        "Signal_raise" => Some(system::native_signal_raise),

        // Zlib natives (stubs)
        "Zlib_compress" => Some(zlib::native_zlib_compress),
        "Zlib_decompress" => Some(zlib::native_zlib_decompress),
        "Gzip_compress" => Some(zlib::native_gzip_compress),
        "Gzip_decompress" => Some(zlib::native_gzip_decompress),

        // Additional Os natives
        "Os_cpuCount" => Some(system::native_os_cpu_count),
        "Os_userName" => Some(system::native_os_user_name),
        "Os_hostName" => Some(system::native_os_host_name),
        "Os_urandom" => Some(system::native_os_urandom),
        "Os_chmod" => Some(system::native_os_chmod),
        "Os_makedirs" => Some(system::native_os_makedirs),
        "Os_symlink" => Some(system::native_os_symlink),
        "Os_readlink" => Some(system::native_os_readlink),
        "Os_kill" => Some(system::native_os_kill),

        _ => None,
    }
}
