// Titrate Alpha 0.2 – bytecode virtual machine: native function lookup
// Precision in every step – richie-rich90454, 2026

use super::super::super::value::NativeFn;
use super::{builtins, file, path, directory, system, net, time, regex, math,
            random, json, string, hash, encoding, subprocess, tempfile,
            thread, mutex, condvar, semaphore, atomic, socket, ssl, sqlite, mmap, zlib, zip,
            multiprocessing};

pub fn lookup_builtin_native(name: &str) -> Option<NativeFn> {
    match name {
        "println" => Some(builtins::native_println),
        "toString" => Some(builtins::native_to_string),
        "parseInt" => Some(builtins::native_parse_int),
        "Ok" => Some(builtins::native_ok),
        "Err" => Some(builtins::native_err),
        "File_readFile" => Some(file::native_file_read),
        "File_writeFile" => Some(file::native_file_write),
        "File_readLines" => Some(file::native_file_read_lines),
        "File_open" => Some(file::native_file_open),
        "File_readLine" => Some(file::native_file_read_line),
        "File_write" => Some(file::native_file_write_content),
        "File_close" => Some(file::native_file_close),
        "File_seek" => Some(file::native_file_seek),
        "File_tell" => Some(file::native_file_tell),
        "File_readBytes" => Some(file::native_file_read_bytes),
        "File_writeBytes" => Some(file::native_file_write_bytes),
        "File_lastModified" => Some(file::native_file_last_modified),
        "File_setModified" => Some(file::native_file_set_modified),
        "File_flush" => Some(file::native_file_flush),
        "File_size" => Some(file::native_file_size),
        "File_truncate" => Some(file::native_file_truncate),
        "File_copy" => Some(file::native_file_copy),
        "File_delete" => Some(file::native_file_delete),
        "String_split" => Some(builtins::native_string_split),
        "Integer_parseOr" => Some(builtins::native_integer_parse_or),
        "String_trim" => Some(builtins::native_string_trim),
        "String_length" => Some(builtins::native_string_length),
        "Path_join" => Some(path::native_path_join),
        "Path_exists" => Some(path::native_path_exists),
        "Path_isFile" => Some(path::native_path_is_file),
        "Path_isDir" => Some(path::native_path_is_dir),
        "Path_basename" => Some(path::native_path_basename),
        "Path_dirname" => Some(path::native_path_dirname),
        "Path_extension" => Some(path::native_path_extension),
        "Path_isSymlink" => Some(path::native_path_is_symlink),
        "Dir_list" => Some(directory::native_dir_list),
        "Dir_create" => Some(directory::native_dir_create),
        "Dir_remove" => Some(directory::native_dir_remove),
        "Dir_removeTree" => Some(directory::native_dir_remove_tree),
        "Sys_args" => Some(system::native_sys_args),
        "Sys_env" => Some(system::native_sys_env),
        "Sys_setEnv" => Some(system::native_sys_set_env),
        "Sys_exit" => Some(system::native_sys_exit),
        "Sys_workingDir" => Some(system::native_sys_working_dir),
        "Sys_setWorkingDir" => Some(system::native_sys_set_working_dir),
        "Sys_sleep" => Some(system::native_sys_sleep),
        "Net_connect" => Some(net::native_net_connect),
        "Net_send" => Some(net::native_net_send),
        "Net_receive" => Some(net::native_net_receive),
        "Net_bind" => Some(net::native_net_bind),
        "Net_accept" => Some(net::native_net_accept),
        "Net_close" => Some(net::native_net_close),
        "Net_getLocalPort" => Some(net::native_net_get_local_port),
        "Net_getLocalAddress" => Some(net::native_net_get_local_address),
        "Net_getRemoteAddress" => Some(net::native_net_get_remote_address),
        "Net_setTimeout" => Some(net::native_net_set_timeout),
        "Http_get" => Some(net::native_http_get),
        "Http_post" => Some(net::native_http_post),
        "Http_put" => Some(net::native_http_put),
        "Http_delete" => Some(net::native_http_delete),
        "Http_patch" => Some(net::native_http_patch),
        "Http_head" => Some(net::native_http_head),
        "Http_setTimeout" => Some(net::native_http_set_timeout),
        "Http_setFollowRedirects" => Some(net::native_http_set_follow_redirects),
        "Dns_lookup" => Some(net::native_dns_lookup),
        "Dns_reverseLookup" => Some(net::native_dns_reverse_lookup),
        "Time_now" => Some(time::native_time_now),
        "Time_sleep" => Some(time::native_time_sleep),
        "Time_format" => Some(time::native_time_format),
        "Time_getYear" => Some(time::native_time_get_year),
        "Time_getMonth" => Some(time::native_time_get_month),
        "Time_getDay" => Some(time::native_time_get_day),
        "Time_getHour" => Some(time::native_time_get_hour),
        "Time_getMinute" => Some(time::native_time_get_minute),
        "Time_getSecond" => Some(time::native_time_get_second),
        "Regex_match" => Some(regex::native_regex_match),
        "Regex_find" => Some(regex::native_regex_find),
        "Regex_replace" => Some(regex::native_regex_replace),
        "Math_sin" => Some(math::native_math_sin),
        "Math_cos" => Some(math::native_math_cos),
        "Math_tan" => Some(math::native_math_tan),
        "Math_asin" => Some(math::native_math_asin),
        "Math_acos" => Some(math::native_math_acos),
        "Math_atan" => Some(math::native_math_atan),
        "Math_atan2" => Some(math::native_math_atan2),
        "Math_ln" => Some(math::native_math_ln),
        "Math_log10" => Some(math::native_math_log10),
        "Math_log2" => Some(math::native_math_log2),
        "Math_exp" => Some(math::native_math_exp),
        "Math_pow" => Some(math::native_math_pow),
        "Math_sqrt" => Some(math::native_math_sqrt),
        "Math_cbrt" => Some(math::native_math_cbrt),
        "Math_abs" => Some(math::native_math_abs),
        "Math_absInt" => Some(math::native_math_abs_int),
        "Math_floor" => Some(math::native_math_floor),
        "Math_ceil" => Some(math::native_math_ceil),
        "Math_round" => Some(math::native_math_round),
        "Math_inf" => Some(math::native_math_inf),
        "Math_nan" => Some(math::native_math_nan),
        "Math_maxDouble" => Some(math::native_math_max_double),
        "Math_minDouble" => Some(math::native_math_min_double),
        "Math_maxInt" => Some(math::native_math_max_int),
        "Math_minInt" => Some(math::native_math_min_int),
        "Random_seed" => Some(random::native_random_seed),
        "Random_nextLong" => Some(random::native_random_next_long),
        "Json_parse" => Some(json::native_json_parse),
        "Json_stringify" => Some(json::native_json_stringify),
        "Env_get" => Some(system::native_env_get),
        "Env_set" => Some(system::native_env_set),
        "Env_vars" => Some(system::native_env_vars),
        "Fs_exists" => Some(system::native_fs_exists),
        "Fs_isFile" => Some(system::native_fs_is_file),
        "Fs_isDir" => Some(system::native_fs_is_dir),
        "Fs_size" => Some(system::native_fs_size),
        "Fs_totalSpace" => Some(system::native_fs_total_space),
        "Fs_freeSpace" => Some(system::native_fs_free_space),
        "Process_id" => Some(system::native_process_id),
        "Process_args" => Some(system::native_process_args),
        "Os_name" => Some(system::native_os_name),
        "Os_arch" => Some(system::native_os_arch),
        "Os_family" => Some(system::native_os_family),
        "String_trimStart" => Some(string::native_string_trim_start),
        "String_trimEnd" => Some(string::native_string_trim_end),
        "String_startsWith" => Some(string::native_string_starts_with),
        "String_endsWith" => Some(string::native_string_ends_with),
        "String_padLeft" => Some(string::native_string_pad_left),
        "String_padRight" => Some(string::native_string_pad_right),
        "String_toUpperCase" => Some(string::native_string_to_uppercase),
        "String_toLowerCase" => Some(string::native_string_to_lower_case),
        "String_replace" => Some(string::native_string_replace),
        "String_fromCharCode" => Some(string::native_string_from_char_code),
        "String_charAt" => Some(string::native_string_char_at),
        "Hash_md5" => Some(hash::native_hash_md5),
        "Hash_sha1" => Some(hash::native_hash_sha1),
        "Hash_sha256" => Some(hash::native_hash_sha256),
        "Hash_sha384" => Some(hash::native_hash_sha384),
        "Hash_sha512" => Some(hash::native_hash_sha512),
        "Hash_sha3_256" => Some(hash::native_hash_sha3_256),
        "Hash_sha3_384" => Some(hash::native_hash_sha3_384),
        "Hash_sha3_512" => Some(hash::native_hash_sha3_512),
        "Hash_blake2b" => Some(hash::native_hash_blake2b),
        "Hash_blake2s" => Some(hash::native_hash_blake2s),
        "Hash_crc32" => Some(hash::native_hash_crc32),
        "Hash_sha224" => Some(hash::native_hash_sha224),
        "Hash_sha3_224" => Some(hash::native_hash_sha3_224),
        "Hash_shake128" => Some(hash::native_hash_shake128),
        "Hash_shake256" => Some(hash::native_hash_shake256),
        "Hasher_new" => Some(hash::native_hasher_new),
        "Hasher_update" => Some(hash::native_hasher_update),
        "Hasher_digest" => Some(hash::native_hasher_digest),
        "Hasher_hexDigest" => Some(hash::native_hasher_hex_digest),
        "Hasher_reset" => Some(hash::native_hasher_reset),
        "Hasher_close" => Some(hash::native_hasher_close),
        "Hmac_compareDigest" => Some(hash::native_hmac_compare_digest),
        "Base64_encode" => Some(encoding::native_base64_encode),
        "Base64_decode" => Some(encoding::native_base64_decode),
        "Hex_encode" => Some(encoding::native_hex_encode),
        "Hex_decode" => Some(encoding::native_hex_decode),
        "Url_encode" => Some(encoding::native_url_encode),
        "Url_decode" => Some(encoding::native_url_decode),
        "Math_nextUp" => Some(math::native_math_next_up),
        "Math_nextDown" => Some(math::native_math_next_down),
        "Math_ulp" => Some(math::native_math_ulp),
        "Math_getExponent" => Some(math::native_math_get_exponent),
        "Math_scalb" => Some(math::native_math_scalb),
        "Math_random" => Some(math::native_math_random),
        "Math_negInf" => Some(math::native_math_neg_inf),
        "Math_fma" => Some(math::native_math_fma),
        "Regex_groupCount" => Some(regex::native_regex_group_count),
        "Regex_findGroups" => Some(regex::native_regex_find_groups),
        "Regex_findWithFlags" => Some(regex::native_regex_find_with_flags),
        "Regex_matchWithFlags" => Some(regex::native_regex_match_with_flags),
        "Dir_walk" => Some(directory::native_dir_walk),
        "Dir_copy" => Some(directory::native_dir_copy),
        "Dir_move" => Some(directory::native_dir_move),
        "Time_dayOfWeek" => Some(time::native_time_day_of_week),
        "Time_dayOfYear" => Some(time::native_time_day_of_year),
        "Time_monotonic" => Some(time::native_time_monotonic),
        "Time_perfCounter" => Some(time::native_time_perf_counter),
        "Time_epochSeconds" => Some(time::native_time_epoch_seconds),
        "Time_nanos" => Some(time::native_time_nanos),
        "Time_millis" => Some(time::native_time_now),
        "Regex_fullMatch" => Some(regex::native_regex_full_match),
        "Regex_subN" => Some(regex::native_regex_sub_n),
        "Double_parseDouble" => Some(builtins::native_double_parse_double),
        "Double_parse" => Some(builtins::native_double_parse_double),
        "Long_parseLong" => Some(builtins::native_long_parse_long),
        "TypeName_of" => Some(builtins::native_type_name_of),
        "Subprocess_run" => Some(subprocess::native_subprocess_run),
        "Subprocess_exec" => Some(subprocess::native_subprocess_exec),
        "Subprocess_popenWrite" => Some(subprocess::native_subprocess_popen_write),
        "Tempfile_create" => Some(tempfile::native_tempfile_create),

        // Thread natives
        "Thread_spawn" => Some(thread::native_thread_spawn),
        "Thread_spawnRunnable" => Some(thread::native_thread_spawn_runnable),
        "Thread_join" => Some(thread::native_thread_join),
        "Thread_sleep" => Some(thread::native_thread_sleep),
        "Thread_yield" => Some(thread::native_thread_yield),
        "Thread_getId" => Some(thread::native_thread_get_id),
        "Thread_currentId" => Some(thread::native_thread_current_id),
        "Thread_detach" => Some(thread::native_thread_detach),

        // Mutex natives
        "Mutex_new" => Some(mutex::native_mutex_new),
        "Mutex_lock" => Some(mutex::native_mutex_lock),
        "Mutex_unlock" => Some(mutex::native_mutex_unlock),
        "Mutex_tryLock" => Some(mutex::native_mutex_try_lock),
        "RecursiveMutex_new" => Some(mutex::native_recursive_mutex_new),
        "RecursiveMutex_lock" => Some(mutex::native_recursive_mutex_lock),
        "RecursiveMutex_unlock" => Some(mutex::native_recursive_mutex_unlock),
        "RecursiveMutex_tryLock" => Some(mutex::native_recursive_mutex_try_lock),

        // SharedMutex natives
        "SharedMutex_new" => Some(mutex::native_shared_mutex_new),
        "SharedMutex_sharedLock" => Some(mutex::native_shared_mutex_shared_lock),
        "SharedMutex_sharedUnlock" => Some(mutex::native_shared_mutex_shared_unlock),
        "SharedMutex_uniqueLock" => Some(mutex::native_shared_mutex_unique_lock),
        "SharedMutex_uniqueUnlock" => Some(mutex::native_shared_mutex_unique_unlock),
        "SharedMutex_trySharedLock" => Some(mutex::native_shared_mutex_try_shared_lock),
        "SharedMutex_tryUniqueLock" => Some(mutex::native_shared_mutex_try_unique_lock),

        // OnceFlag natives
        "OnceFlag_new" => Some(mutex::native_once_flag_new),
        "OnceFlag_callOnce" => Some(mutex::native_once_flag_call_once),

        // Condvar natives
        "CondVar_new" => Some(condvar::native_cv_new),
        "CondVar_wait" => Some(condvar::native_cv_wait),
        "CondVar_waitFor" => Some(condvar::native_cv_wait_for),
        "CondVar_notifyOne" => Some(condvar::native_cv_notify_one),
        "CondVar_notifyAll" => Some(condvar::native_cv_notify_all),

        // Semaphore natives
        "Semaphore_new" => Some(semaphore::native_sem_new),
        "Semaphore_acquire" => Some(semaphore::native_sem_acquire),
        "Semaphore_release" => Some(semaphore::native_sem_release),
        "Semaphore_tryAcquire" => Some(semaphore::native_sem_try_acquire),
        "Semaphore_availablePermits" => Some(semaphore::native_sem_available_permits),

        // AtomicInt natives
        "AtomicInt_new" => Some(atomic::native_atomic_int_new),
        "AtomicInt_get" => Some(atomic::native_atomic_int_get),
        "AtomicInt_set" => Some(atomic::native_atomic_int_set),
        "AtomicInt_fetchAdd" => Some(atomic::native_atomic_int_fetch_add),
        "AtomicInt_fetchSub" => Some(atomic::native_atomic_int_fetch_sub),
        "AtomicInt_compareAndSwap" => Some(atomic::native_atomic_int_compare_and_swap),
        "AtomicInt_fetchOr" => Some(atomic::native_atomic_int_fetch_or),
        "AtomicInt_fetchAnd" => Some(atomic::native_atomic_int_fetch_and),
        "AtomicInt_fetchXor" => Some(atomic::native_atomic_int_fetch_xor),
        "AtomicInt_exchange" => Some(atomic::native_atomic_int_exchange),

        // AtomicBool natives
        "AtomicBool_new" => Some(atomic::native_atomic_bool_new),
        "AtomicBool_get" => Some(atomic::native_atomic_bool_get),
        "AtomicBool_set" => Some(atomic::native_atomic_bool_set),
        "AtomicBool_compareAndSwap" => Some(atomic::native_atomic_bool_compare_and_swap),

        // AtomicLong natives
        "AtomicLong_new" => Some(atomic::native_atomic_long_new),
        "AtomicLong_get" => Some(atomic::native_atomic_long_get),
        "AtomicLong_set" => Some(atomic::native_atomic_long_set),
        "AtomicLong_fetchAdd" => Some(atomic::native_atomic_long_fetch_add),
        "AtomicLong_fetchSub" => Some(atomic::native_atomic_long_fetch_sub),
        "AtomicLong_compareAndSwap" => Some(atomic::native_atomic_long_compare_and_swap),

        // AtomicRef natives
        "AtomicRef_new" => Some(atomic::native_atomic_ref_new),
        "AtomicRef_get" => Some(atomic::native_atomic_ref_get),
        "AtomicRef_set" => Some(atomic::native_atomic_ref_set),
        "AtomicRef_compareAndSwap" => Some(atomic::native_atomic_ref_compare_and_swap),

        // TCP Socket natives
        "Socket_new" => Some(socket::native_socket_new),
        "Socket_connect" => Some(socket::native_socket_connect),
        "Socket_bind" => Some(socket::native_socket_bind),
        "Socket_listen" => Some(socket::native_socket_listen),
        "Socket_accept" => Some(socket::native_socket_accept),
        "Socket_send" => Some(socket::native_socket_send),
        "Socket_recv" => Some(socket::native_socket_recv),
        "Socket_close" => Some(socket::native_socket_close),
        "Socket_setTimeout" => Some(socket::native_socket_set_timeout),
        "Socket_setNoDelay" => Some(socket::native_socket_set_no_delay),

        // UDP Socket natives
        "UdpSocket_new" => Some(socket::native_udp_socket_new),
        "UdpSocket_bind" => Some(socket::native_udp_socket_bind),
        "UdpSocket_sendTo" => Some(socket::native_udp_socket_send_to),
        "UdpSocket_recvFrom" => Some(socket::native_udp_socket_recv_from),
        "UdpSocket_close" => Some(socket::native_udp_socket_close),
        "UdpSocket_setTimeout" => Some(socket::native_udp_socket_set_timeout),
        "UdpSocket_lastSenderHost" => Some(socket::native_udp_socket_last_sender_host),
        "UdpSocket_lastSenderPort" => Some(socket::native_udp_socket_last_sender_port),
        "Socket_getAddrInfo" => Some(socket::native_socket_get_addr_info),
        "Socket_inetPton" => Some(socket::native_socket_inet_pton),
        "Socket_inetNtop" => Some(socket::native_socket_inet_ntop),
        "Socket_createConnection" => Some(socket::native_socket_create_connection),
        "Socket_createServer" => Some(socket::native_socket_create_server),
        "Socket_getLocalAddress" => Some(socket::native_socket_get_local_address),
        "Socket_getRemoteAddress" => Some(socket::native_socket_get_remote_address),
        "Socket_getLocalPort" => Some(socket::native_socket_get_local_port),
        "Socket_getRemotePort" => Some(socket::native_socket_get_remote_port),
        "Socket_setReuseAddr" => Some(socket::native_socket_set_reuse_addr),
        "Socket_setBroadcast" => Some(socket::native_socket_set_broadcast),
        "Socket_setKeepAlive" => Some(socket::native_socket_set_keep_alive),
        "Socket_setLinger" => Some(socket::native_socket_set_linger),

        // SSL natives (stubs)
        "Ssl_contextNew" => Some(ssl::native_ssl_context_new),
        "Ssl_connect" => Some(ssl::native_ssl_connect),
        "Ssl_send" => Some(ssl::native_ssl_send),
        "Ssl_recv" => Some(ssl::native_ssl_recv),
        "Ssl_close" => Some(ssl::native_ssl_close),
        "Ssl_peerCertificate" => Some(ssl::native_ssl_peer_certificate),
        "Ssl_contextClose" => Some(ssl::native_ssl_context_close),
        "Ssl_getPeerCertHash" => Some(ssl::native_ssl_get_peer_cert_hash),

        // SQLite natives (stubs)
        "Sqlite_open" => Some(sqlite::native_sqlite_open),
        "Sqlite_execute" => Some(sqlite::native_sqlite_execute),
        "Sqlite_query" => Some(sqlite::native_sqlite_query),
        "Sqlite_close" => Some(sqlite::native_sqlite_close),
        "Sqlite_lastInsertId" => Some(sqlite::native_sqlite_last_insert_id),
        "Sqlite_nextRow" => Some(sqlite::native_sqlite_next_row),
        "Sqlite_getInt" => Some(sqlite::native_sqlite_get_int),
        "Sqlite_getString" => Some(sqlite::native_sqlite_get_string),
        "Sqlite_getDouble" => Some(sqlite::native_sqlite_get_double),
        "Sqlite_columnCount" => Some(sqlite::native_sqlite_column_count),
        "Sqlite_columnName" => Some(sqlite::native_sqlite_column_name),
        "Sqlite_closeResult" => Some(sqlite::native_sqlite_close_result),
        "Sqlite_executePrepared" => Some(sqlite::native_sqlite_execute_prepared),
        "Sqlite_backup" => Some(sqlite::native_sqlite_backup),

        // Mmap natives (stubs)
        "Mmap_open" => Some(mmap::native_mmap_open),
        "Mmap_close" => Some(mmap::native_mmap_close),
        "Mmap_get" => Some(mmap::native_mmap_get),
        "Mmap_set" => Some(mmap::native_mmap_set),
        "Mmap_size" => Some(mmap::native_mmap_size),
        "Mmap_flush" => Some(mmap::native_mmap_flush),

        // Signal natives (stubs)
        "Signal_register" => Some(system::native_signal_register),
        "Signal_raise" => Some(system::native_signal_raise),

        // Zlib natives (stubs)
        "Zlib_compress" => Some(zlib::native_zlib_compress),
        "Zlib_decompress" => Some(zlib::native_zlib_decompress),
        "Gzip_compress" => Some(zlib::native_gzip_compress),
        "Gzip_decompress" => Some(zlib::native_gzip_decompress),

        // Zip archive natives
        "ZipFile_open" => Some(zip::native_zipfile_open),
        "ZipFile_entryCount" => Some(zip::native_zipfile_entry_count),
        "ZipFile_entryName" => Some(zip::native_zipfile_entry_name),
        "ZipFile_readEntry" => Some(zip::native_zipfile_read_entry),
        "ZipFile_extractAll" => Some(zip::native_zipfile_extract_all),
        "ZipFile_close" => Some(zip::native_zipfile_close),
        "ZipWriter_open" => Some(zip::native_zipwriter_open),
        "ZipWriter_addEntry" => Some(zip::native_zipwriter_add_entry),
        "ZipWriter_close" => Some(zip::native_zipwriter_close),

        // Additional Os natives
        "Os_cpuCount" => Some(system::native_os_cpu_count),
        "Os_userName" => Some(system::native_os_user_name),
        "Os_hostName" => Some(system::native_os_host_name),
        "Os_urandom" => Some(system::native_os_urandom),
        "Os_chmod" => Some(system::native_os_chmod),
        "Os_makedirs" => Some(system::native_os_makedirs),
        "Os_symlink" => Some(system::native_os_symlink),
        "Os_readlink" => Some(system::native_os_readlink),
        "Os_kill" => Some(system::native_os_kill),
        "Os_environ" => Some(system::native_os_environ),
        "Os_umask" => Some(system::native_os_umask),
        "Os_scandir" => Some(system::native_os_scandir),
        "Os_environMap" => Some(system::native_os_environ_map),
        "Os_getpid" => Some(system::native_process_id),
        "Os_getcwd" => Some(system::native_sys_working_dir),
        "Os_chdir" => Some(system::native_sys_change_dir),
        "Os_getenv" => Some(system::native_env_get),
        "Os_setenv" => Some(system::native_env_set),
        "Os_unsetenv" => Some(system::native_env_unset),
        "Os_system" => Some(system::native_os_system),
        "Os_uname" => Some(system::native_os_uname),
        "Os_getppid" => Some(system::native_os_getppid),
        "Os_strerror" => Some(system::native_os_strerror),
        "Os_removedirs" => Some(system::native_os_removedirs),
        "Os_renames" => Some(system::native_os_renames),
        "Os_replace" => Some(system::native_os_replace),
        "Os_link" => Some(system::native_os_link),
        "Os_utime" => Some(system::native_os_utime),
        "Os_lstat" => Some(system::native_os_lstat),
        "Os_access" => Some(system::native_os_access),
        "Os_release" => Some(system::native_os_release),
        "Os_version" => Some(system::native_os_version),
        "Titrate_version" => Some(system::native_titrate_version),
        "Gc_collect" => Some(system::native_gc_collect),

        // Multiprocessing natives
        "Process_spawn" => Some(multiprocessing::native_process_spawn),
        "Process_join" => Some(multiprocessing::native_process_join),
        "Process_terminate" => Some(multiprocessing::native_process_terminate),
        "Queue_new" => Some(multiprocessing::native_queue_new),
        "Queue_send" => Some(multiprocessing::native_queue_send),
        "Queue_recv" => Some(multiprocessing::native_queue_recv),
        "Queue_close" => Some(multiprocessing::native_queue_close),

        _ => None,
    }
}
