/*
 * titrate_native.h - C-ABI native runtime bridge for the Titrate LLVM backend.
 *
 * This header declares the types and functions exposed by the titrate_native
 * Rust crate. It is consumed by C/C++ code (and by hand-written LLVM IR
 * declarations) that need to interoperate with Titrate values.
 *
 * Generated by hand; cbindgen could regenerate this from src/lib.rs.
 */
#ifndef TITRATE_NATIVE_H
#define TITRATE_NATIVE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Type tags for the TitrateValue tagged union                        */
/* ------------------------------------------------------------------ */

#define TV_VOID            0
#define TV_NULL            1
#define TV_BOOL            2
#define TV_BYTE            3
#define TV_SHORT           4
#define TV_INT             5
#define TV_LONG            6
#define TV_VAST            7
#define TV_UVAST           8
#define TV_FLOAT           9
#define TV_DOUBLE         10
#define TV_CHAR           11
#define TV_STRING         12
#define TV_ARRAY          13
#define TV_CLASS_INSTANCE 14
#define TV_RESULT_OK      15
#define TV_RESULT_ERR     16
#define TV_ENUM_INSTANCE  17
#define TV_TUPLE          18
#define TV_HALF           19
#define TV_QUAD           20
#define TV_HANDLE         21

/* ------------------------------------------------------------------ */
/* C-ABI value types                                                  */
/* ------------------------------------------------------------------ */

/* UTF-8 string: length + pointer (buffer is NOT NUL-terminated). */
typedef struct {
    int64_t  len;
    uint8_t *ptr;
} TitrateString;

/* Array of TitrateValue: length + heap-allocated data pointer. */
typedef struct {
    int64_t        len;
    struct TitrateValue *data;
} TitrateArray;

/* Opaque handle for complex values (class instances, file handles, etc.). */
typedef struct {
    int64_t id;
    int32_t type_tag;
} TitrateHandle;

/* 16-byte payload union. */
typedef union {
    int8_t          bool_val;
    int8_t          byte_val;
    int16_t         short_val;
    int32_t         int_val;
    int64_t         long_val;
    __int128        vast_val;     /* may not be available on all compilers */
    unsigned __int128 uvast_val;
    float           float_val;
    double          double_val;
    uint32_t        char_val;
    TitrateString   string;
    TitrateArray    array;
    TitrateHandle   handle;
    uint8_t         raw[16];
} TitratePayload;

/* The canonical C-ABI value: tag + 16-byte payload (24 bytes total). */
typedef struct TitrateValue {
    int32_t        tag;
    int32_t        _pad;
    TitratePayload payload;
} TitrateValue;

/* ------------------------------------------------------------------ */
/* Direct C-ABI helpers                                               */
/* ------------------------------------------------------------------ */

/* Print a UTF-8 string followed by a newline. */
void titrate_println(int64_t len, const uint8_t *ptr);

/* Concatenate two strings into a freshly allocated buffer. */
uint8_t *titrate_string_concat(int64_t a_len, const uint8_t *a_ptr,
                               int64_t b_len, const uint8_t *b_ptr,
                               int64_t *out_len);

/* Free a buffer returned by titrate_string_concat or titrate_malloc. */
void titrate_free(uint8_t *ptr);

/* Allocate `size` bytes of heap memory. */
uint8_t *titrate_malloc(int64_t size);

/* Primitive printers. */
void titrate_println_int(int64_t v);
void titrate_println_double(double v);
void titrate_println_bool(int32_t v);
void titrate_println_char(int32_t v);

/* ------------------------------------------------------------------ */
/* Generic native dispatch bridge                                     */
/* ------------------------------------------------------------------ */

/* Dispatch a native function call by name. */
int32_t titrate_native_call(const uint8_t *name_ptr, int64_t name_len,
                            const uint8_t *args_ptr, int64_t args_count,
                            uint8_t *result_ptr, int64_t *result_cap);

/* ------------------------------------------------------------------ */
/* Per-function C-ABI wrappers (titrate_<NativeName>)                 */
/* ------------------------------------------------------------------ */

/* Every native function is wrapped as:
 *   TitrateValue titrate_<Name>(const TitrateValue *args, size_t arg_count);
 * See wrappers.rs for the full list of 359 wrappers.
 */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TITRATE_NATIVE_H */
